### ISSUE TITLE
Reimplement playback

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#404]
Reimplement playback using `requestAnimationFrame`

* Should consider whether looping through images (current technique) or canvas animation is preferable
* Consider canvas optimisations (eg off screen canvas)
  *  https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas

## Todo

- [x] Add requestAnimationFrameHook
- [x] Add React context producer for managing current frame number
- [x] Click play button to start playback
- [x] Click stop button to stop playback
- [x] Loop through frame number in the status toolbar
- [x] Highlight the current frame in the timeline
- [x] Scroll timeline on playback
- [ ] Loop through frames in the preview area
